### ISSUE TITLE
No app config

### ISSUE THREAD

**Issue by FANGOD** [yueyoum/duckadmin#1]
做个缓存管理页面,之前一直是按官方eg撸的,然后试了一下这个,比较简单,不太够用
我照着demo写的,出现下面的问题Django==1.11.5
```
Unhandled exception in thread started by <function wrapper at 0x7f6d867f75d0>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/checks.py", line 25, in check_admin_app
    errors.extend(site.check(app_configs))
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/admin/sites.py", line 80, in check
    if modeladmin.model._meta.app_config in app_configs:
  File "/home/share/itpserver/bean/duckadmin/forms.py", line 79, in __getattr__
    return self.form_class_attr(item)
  File "/home/share/itpserver/bean/duckadmin/forms.py", line 66, in form_class_attr
    return getattr(self.form_cls, key)
AttributeError: type object 'CacheManagerForm' has no attribute 'app_config'

```

**Comment by FANGOD** [comment]
好吧,原来app_label是config的一部分

**Comment by FANGOD** [comment]
实现太少不够用
